export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const PLANETS_SEARCH_SUCCESS = "PLANETS_SEARCH_SUCCESS";
export const PLANETS_SEARCH_FAILURE = "PLANETS_SEARCH_FAILURE";